In [1]:
import numpy as np

In [2]:
l1 = [20,6,5,20]
l2 = np.array(l1)
print(type(l2), l2)

<class 'numpy.ndarray'> [20  6  5 20]


In [3]:
l3 = [20,True,'56.0',29.7]
l4 = np.array(l3,dtype = float) # changing the data type

In [4]:
l4

array([20. ,  1. , 56. , 29.7])

In [8]:
b = np.array([[1.8,2,3],[4,5,6],
              [6,10.4,3],[4,5,8]])
b

array([[ 1.8,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 6. , 10.4,  3. ],
       [ 4. ,  5. ,  8. ]])

In [9]:
b = b.astype(int) # type casting
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6, 10,  3],
       [ 4,  5,  8]])

In [14]:
print(b.ndim)

print(b.dtype)
print(b.shape)
print(b.size)

2
int32
(4, 3)
12


In [15]:
b = b.astype(float)
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 6., 10.,  3.],
       [ 4.,  5.,  8.]])

In [16]:
arr_1 = np.array([[10,-23,45],[235,56,82],[100,45,76.4]])
arr_2 = np.array([[33,24,56],[315,567,3],[-56,21.5,67]])

In [20]:
print(arr_1+arr_2, "\n","\n", arr_1+25,"\n","\n", arr_1%arr_2,"\n","\n", arr_1 / arr_2, "\n","\n",arr_1*3 )

[[ 43.    1.  101. ]
 [550.  623.   85. ]
 [ 44.   66.5 143.4]] 
 
 [[ 35.    2.   70. ]
 [260.   81.  107. ]
 [125.   70.  101.4]] 
 
 [[ 10.    1.   45. ]
 [235.   56.    1. ]
 [-12.    2.    9.4]] 
 
 [[ 0.3030303  -0.95833333  0.80357143]
 [ 0.74603175  0.09876543 27.33333333]
 [-1.78571429  2.09302326  1.14029851]] 
 
 [[ 30.  -69.  135. ]
 [705.  168.  246. ]
 [300.  135.  229.2]]


In [22]:
# np.where(cond,x,y)
a = np.array([[10,20],
              [30,40],
              [50,60]])
a = np.where(a>=30, a+100, a-40)
a

array([[-30, -20],
       [130, 140],
       [150, 160]])

In [24]:
a = np.where(((a == 10) | (a == 20)), 1, 0 )
a

array([[0, 0],
       [0, 0],
       [0, 0]])

In [35]:
c = np.array([[10,20],
              [30,40],
              [50,60]])

In [36]:
c = np.where(c <= 30, c+5,c-5)
c

array([[15, 25],
       [35, 35],
       [45, 55]])

In [37]:
c = np.where(((c==10) | (c== 25) |(c == 50)), 30, c)
c

array([[15, 30],
       [35, 35],
       [45, 55]])

In [48]:
a2 = np.array(range(8))
print(a2)
print(np.where(a2%2==0, 'even', 'odd'))

[0 1 2 3 4 5 6 7]
['even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd']


In [49]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.eye(3,3,-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [51]:
np.eye(3,3,1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [97]:
np.random.seed(88)
np.random.random((5,2))

array([[0.64755105, 0.50714969],
       [0.52834138, 0.8962852 ],
       [0.69999119, 0.7142971 ],
       [0.71733838, 0.22281946],
       [0.17515452, 0.45684149]])

In [83]:
np.random.randint(3,20,10)

array([ 4, 14,  7, 10, 10, 10,  9, 13, 16,  6])

In [98]:

np.random.randint(1,10,(3,3))

array([[8, 8, 7],
       [7, 4, 2],
       [1, 9, 7]])

In [99]:
np.random.randn(1,3,2)

array([[[-0.83431154,  0.54036515],
        [-1.30409537, -0.92649285],
        [ 1.06389431, -0.45964077]]])

In [101]:
np.random.randn(1,3)

TypeError: 'tuple' object cannot be interpreted as an integer