## Numpy - Numerical Python -- deals with numerical data in form of arrays

In [153]:
import numpy as np 

### creating Array 

In [ ]:
# array can be created using a pre defined List, set, tuple by the given syntax
l_1 = [20, 6, 4]

# String, float, int, bool  --> String
# float, int  --> Float

l_2 = np.array(l_1)
print(type(l_2), l_2)

<class 'numpy.ndarray'> [20  6  4]


In [ ]:
l3 = [12.9, 34 ,'55', True]  #   1. string  , 2. float  , 3. integer

l4_arr=np.array(l3, dtype=float)
print(l4_arr, l4_arr.ndim)

[12.9 34.  55.   1. ] 1


### creating a 2D array

In [ ]:
np.array([100,200,300]) # 1D

array([10., 20., 30.])

In [ ]:
b = np.array([[1.8,2,34],
             [4,5,67],
             [7,9,890],
             [1,1,128]])

b= b.astype(int) # typecasting
print(b) 
# all values in the column should be of same lenght
# string -Numpy - <U

# b/10

[[  1   2  34]
 [  4   5  67]
 [  7   9 890]
 [  1   1 128]]


In [ ]:
b.ndim # checking dimension

b.dtype # data type check

b.shape # shape ( rows, columns)

# b.size # total number of elements in array (rows*columns)

(4, 3)

### type conversion of a predefined array


In [ ]:
b = b.astype(float)
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 1.,  1., 12.]])

### operations on array


In [ ]:
arr_3 = np.array([[10,-20,30],
                [100,200,300],
                [1,2.5,3],
                [5,6,7]])

arr_4 = np.array([[10,12.0,30],
                    [100,800,300],
                    [12.55,2,35.55],
                    [5,6,7]])

display(arr_3 + 20, arr_3 + arr_4,  arr_3 - arr_4, 
        arr_4//5, arr_4 % 2, arr_3 * arr_4*arr_3 )

array([[ 30. ,   0. ,  50. ],
       [120. , 220. , 320. ],
       [ 21. ,  22.5,  23. ],
       [ 25. ,  26. ,  27. ]])

array([[  20.  ,   -8.  ,   60.  ],
       [ 200.  , 1000.  ,  600.  ],
       [  13.55,    4.5 ,   38.55],
       [  10.  ,   12.  ,   14.  ]])

array([[ 0.000e+00, -3.200e+01,  0.000e+00],
       [ 0.000e+00, -6.000e+02,  0.000e+00],
       [-1.155e+01,  5.000e-01, -3.255e+01],
       [ 0.000e+00,  0.000e+00,  0.000e+00]])

array([[  2.,   2.,   6.],
       [ 20., 160.,  60.],
       [  2.,   0.,   7.],
       [  1.,   1.,   1.]])

array([[0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ],
       [0.55, 0.  , 1.55],
       [1.  , 0.  , 1.  ]])

array([[1.0000e+03, 4.8000e+03, 2.7000e+04],
       [1.0000e+06, 3.2000e+07, 2.7000e+07],
       [1.2550e+01, 1.2500e+01, 3.1995e+02],
       [1.2500e+02, 2.1600e+02, 3.4300e+02]])

### np.where(condn, x, y)

In [ ]:
a = np.array([[10,20],
              [30,40],
              [50,60]])

np.where(a >= 30)

(array([1, 1, 2, 2]), array([0, 1, 0, 1]))

In [ ]:
np.where(a >= 30 , -1 , 0)

array([[ 0,  0],
       [-1, -1],
       [-1, -1]])

In [ ]:
np.where(((a == 30) | (a== 50) | (a==60)), 304060, a) # (condition, o/p when condn True, o/p when condn False)

array([[    10,     20],
       [304060,     40],
       [304060, 304060]])

In [ ]:
a[:,0]= np.where(((a[:, 0] == 30) | (a[:, 0]== 50) | (a[:, 0]==40)), 30406000, a[:, 0])

print(a)

[[      10       20]
 [30406000       40]
 [30406000       60]]


In [ ]:
np.where((a == 30)|(a==20) , a , 0)

array([[ 0, 20],
       [30,  0],
       [ 0,  0]])

In [ ]:
a.shape

(3, 2)

In [ ]:
a2 = np.array(range(8))
print(a2)
np.where(a2%2==0, 'even' , 'odd')

[0 1 2 3 4 5 6 7]


array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd'],
      dtype='<U4')

In [ ]:
np.random.seed(2021)  # this will freeze the randomness , so everytim - when seed 55 is given , u get same values
rm_arr= np.random.random((3,2)) # this will generate Random array -- decimal random values
rm_arr

array([[0.60597828, 0.73336936],
       [0.13894716, 0.31267308],
       [0.99724328, 0.12816238]])

In [ ]:
a

array([[      10,       20],
       [30406000,       40],
       [30406000,       60]])

In [ ]:
np.where(a>=40, rm_arr, 0)

array([[0.        , 0.        ],
       [0.        , 0.31267308],
       [0.99724328, 0.12816238]])

In [ ]:
a2 = a+10

display(a2, a)

np.where(a>=40 , a2, a)

array([[20, 30],
       [40, 50],
       [60, 70]])

array([[10, 20],
       [30, 40],
       [50, 60]])

array([[10, 20],
       [30, 50],
       [60, 70]])

### reshaping arrays

In [ ]:
a=np.arange(2.2, 13.6, .78)**2
a.size
a

array([  4.84  ,   8.8804,  14.1376,  20.6116,  28.3024,  37.21  ,
        47.3344,  58.6756,  71.2336,  85.0084, 100.    , 116.2084,
       133.6336, 152.2756, 172.1344])

In [ ]:
a3= a.reshape(-1,5) # Reshape Will create 2D arrray from 1 d array , (rows, columns)
# a3= a3.reshape(15,)  
# a3.shape
a3

array([[  4.84  ,   8.8804,  14.1376,  20.6116,  28.3024],
       [ 37.21  ,  47.3344,  58.6756,  71.2336,  85.0084],
       [100.    , 116.2084, 133.6336, 152.2756, 172.1344]])

### flatten an array

In [ ]:
a3=a3.flatten() #always for creating 1D array
a3.shape

(15,)

### checking unique elements

In [ ]:
# Tuple Unpacking example
a, b = 10,12
print(a,b)

10 12


In [ ]:
arr1 = np.array([[1,2,2],
                 [4,5,5],
                 [4,8,9]])
np.unique(arr1) # only unique values given form the array
unique_values, value_count = np.unique(arr1, return_counts=True)

print('unique_values',unique_values,
      'value_count', value_count)

unique_values [1 2 4 5 8 9] value_count [1 2 2 2 1 1]


### np.arange(start,stop,step)

Return evenly spaced values within a given interval.

numpy.arange( start(default = 0) , stop , step(default = 1) )


In [ ]:
np.arange(2.1, 8.5, 0.255)

array([2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1])

In [ ]:
np.arange(2, 21.88, 0.5)

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. ,
       18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5])

### linspace(start,  stop,   num = 50)
Return evenly spaced numbers over a specified interval. - BOTH LOW & HIGH are Inclusive


#### np.linspace  (start , stop , num=50) By Default 50  occurances


In [ ]:
np.linspace(1,10,50, retstep=True)  # retstep - return step - differnec b/w 2 value

(array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
         1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
         2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
         3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
         4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
         5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
         6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
         7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
         8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
         9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]),
 0.1836734693877551)

### np.random

It is used to create random number arrays:

In [6]:
import numpy as np

In [7]:
np.random.seed(5000)  # any positive integer number - >0
np.random.random((5,2))# (rows, cols)

array([[0.22904787, 0.36066976],
       [0.727653  , 0.1126678 ],
       [0.60777065, 0.81574946],
       [0.98126938, 0.06374484],
       [0.79995975, 0.09694856]])

In [8]:
np.random.randn(2,2) #positive & negative numbers

array([[ 1.67824248, -1.02596417],
       [-0.02176213,  0.53048021]])

In [9]:
np.random.seed(50)

np.random.randint(0,100,40) # will generate 1D output

np.random.randint(0,10, (4,4))# (rows, cols) - will generate 2D output

array([[2, 0, 3, 0],
       [0, 7, 3, 8],
       [7, 4, 4, 0],
       [0, 3, 3, 1]])

In [ ]:
np.random.seed(50)

a = np.random.normal(8,2,50) # np.random.normal(mean, std, number of observations)

display(np.mean(a), np.std(a), a.size, a)

# normaly distributed data - mean around 0 and std around 1

8.186312635066972

2.003391826740795

50

array([ 4.87929578,  7.93804479,  6.75814315,  5.07083903, 10.82389224,
        7.04653571,  6.43906157, 10.14053547,  5.43541481,  5.3450422 ,
        8.25267528,  9.72438743,  9.39347393,  7.33086963,  6.00494787,
       11.19781659, 14.62815069,  9.97554092,  8.24773251,  9.48557079,
        7.2120883 ,  8.29623164,  7.17553109,  7.67856988,  8.27906295,
        8.57093874,  7.43747601, 11.42181463,  7.70046672,  9.38061344,
       10.19041902, 10.67681741,  5.26203666,  8.97285526,  9.50704336,
        8.72692919,  7.37057904, 10.74656234,  6.75116567,  8.75150799,
        7.59916737,  9.48607612,  9.71472391,  4.98762143,  4.66729566,
        7.56201039,  7.28228314,  8.75705539,  9.36843073,  5.66428787])

Variance & std

In [ ]:
v2 = np.array( [1,3,5,2,4]  )
print(np.var(v2))
print(np.std(v2))
np.mean(v2)

In [ ]:
v1 = np.array( [ 1,10,16,22,27,31,50,60,100,101, 300, 500, 330 ]  )
np.var(v1)
np.std(v1)
np.mean(v1)

### Transpose

In [ ]:
arr = np.arange(10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
arr.T
np.transpose(arr)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

### np.zeros

### np.full

### np.eye

### np.ones


In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full((3,3), 16)# np.full(shape, value)

array([[16, 16, 16],
       [16, 16, 16],
       [16, 16, 16]])

In [ ]:
np.eye(3,3) # print 1 on the diagonal

np.eye(3,3,-1) # print 1 below the diagonal

np.eye(3,3,1) # print 1 above the diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
np.ones(5) # 1D array of size 5 - having all 1's

np.ones((2,2)) # 2D array of size 5 - having all 1's

array([[1., 1.],
       [1., 1.]])

### indexing 

In [156]:
np.random.seed(5)
f = np.random.randint(1,40,(4,5))
f

array([[36, 15, 39, 17, 10],
       [ 9, 37, 28, 31, 17],
       [ 8, 13, 16, 17, 28],
       [14, 12,  2, 31, 21]])

In [157]:
f[-1,-1]

f[:,0]

f[0:2, 1:3]

f[:, :3]=100

f[-1,-1]=29

f

array([[100, 100, 100,  17,  10],
       [100, 100, 100,  31,  17],
       [100, 100, 100,  17,  28],
       [100, 100, 100,  31,  29]])

In [159]:
f[ [1, 2,3 ], [3,3,3]]

array([31, 17, 31])

In [ ]:
#Get values in a range
f[ [2,0,3] ,  [-1,0,-2]  ]

f[ 0:2 ,  [-1,0,-2]  ]

array([[ 10, 100,  17],
       [ 17, 100,  31]])

In [ ]:
f[-2:] # will pick rows and all cols

array([[100, 100, 100,  17,  28],
       [100, 100, 100,  31,  29]])

In [ ]:
f[  [3,1,-1],   -3:   ] # [rows, columns]

array([[100,  31,  29],
       [100,  31,  17],
       [100,  31,  29]])

In [ ]:
f[-1,2] = 700

In [ ]:
f[0:4] = 10

In [163]:
f[:] = 1 # include everthing
f

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
f[[0,1],[2,2]]

array([1, 1])

In [164]:
f[[3,2,0],2:4]

array([[1, 1],
       [1, 1],
       [1, 1]])

### min, max
### argmax, argmin, argwhere

In [165]:
arr2 = np.array([[1,2],
                [8,19],
                [90,5],
                [999,0]])
arr2.max()

999

In [173]:
#gives the maximum value
arr2.max(axis=0) #   axis=1 ---> rows,     axis=0 ---> cols

# # # gives the index of maximum value  - by coverting array in 1D
arr2.argmax()   #  [1,2,8,19,90,5,999,0]
arr2.argmax(axis=0)   #  [1,8,90,999], [2,19,5,0]
arr2.argmax(axis=1)   #  [1,2], [8,9],[90,5], [999,0]]

# # # # # # gives the minimum value
# arr2.min()

# # # # # # # # gives the index of minimum value  - by firstly coverting array in 1D in the backend
arr2.argmin()

array([1, 1, 0, 0])

In [174]:
np.argwhere(arr2 == arr2.max()) # 2D index  where the condition satisfies

array([[3, 0]])

### filtering values

In [176]:
arr = np.arange(1,21).reshape(5,4)
arr[-1,-1]=17
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 17]])

In [177]:
arr[arr >= 15] # gives values

array([15, 16, 17, 18, 19, 17])

### np.sum()

In [ ]:
np.sum(arr) # no axis specified -- all values are added up 

207

In [ ]:
np.sum(arr, axis  = 0) # adding column value

array([45, 50, 55, 57])

In [ ]:
np.sum(arr, axis = 1) # adding every single row value

array([10, 26, 42, 58, 71])

In [178]:
np.sum(arr, axis=0 , where = arr>17) 

array([ 0, 18, 19,  0])

### some more functions

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 17]])

In [ ]:
np.mean(arr)

10.35

In [ ]:
np.cumprod(arr) # cumlative product
np.cumsum(arr) # cumlative sum

array([         1,          2,          6,         24,        120,
              720,       5040,      40320,     362880,    3628800,
         39916800,  479001600, 1932053504, 1278945280, 2004310016,
       2004189184, -288522240, -898433024,  109641728, 1863909376],
      dtype=int32)

In [179]:
a = np.array([[10.89451,20.7121258],
             [55.545121,66.54584150]])
a

array([[10.89451  , 20.7121258],
       [55.545121 , 66.5458415]])

In [181]:
display(np.round(a), 
        np.around(a,2))

array([[11., 21.],
       [56., 67.]])

array([[10.89, 20.71],
       [55.55, 66.55]])

In [ ]:
#Calcualting mean
np.mean(arr)

10.35

In [ ]:
np.absolute(-55) # convert negative values to positive 
np.abs(-55)

55

In [ ]:
#Calcualting Standard Deviation
np.std(a)

23.213972410737075

In [ ]:
np.log2(a) # log base 2
np.log10(a) # log base 10
np.log(7) # natural log

np.exp(np.log(7)) # getting logged value back to scale

6.999999999999999

In [183]:
np.exp(np.log(7))

6.999999999999999

In [188]:
np.log(7)

1.9459101490553132

In [184]:
np.sin(45)

0.8509035245341184

In [187]:
np.arange(10.3, 15.5)

array([10.3, 11.3, 12.3, 13.3, 14.3, 15.3])