In [1]:
import numpy as np
import pandas as pd

In [7]:
arr_list = np.array([10,20,30,40,50])
print(arr_list.ndim)
print(arr_list)

1
[10 20 30 40 50]


In [8]:
arr_list.astype(float)

array([10., 20., 30., 40., 50.])

In [13]:
arr_list1 = np.array([[10,20,30.5],
                      [20.4,17,45],
                      [435,100,346]],
                    dtype = int)
arr_list1

array([[ 10,  20,  30],
       [ 20,  17,  45],
       [435, 100, 346]])

In [14]:
arr_list1[0,1]

20

In [18]:
arr_list1[2,2]

346

In [19]:
arr_list1[1,:]

array([20, 17, 45])

In [21]:
arr_list1[[2,1],0]

array([435,  20])

In [25]:
# List to Series
l1 = [10,'20',30,40,50.6]
pd.Series(l1, name='series1')

0      10
1      20
2      30
3      40
4    50.6
Name: series1, dtype: object

In [29]:
d = pd.Series({'a':10,'b':20,'c':30},name = 'dictionary')
d

a    10
b    20
c    30
Name: dictionary, dtype: int64