# PANDAS

In [1]:
import pandas as pd
import numpy as np   # to make data in form of array

In [9]:
li = [10, 20, 30, 40, 60]

ar = np.array(li)
print(ar)
ar.ndim # check dimension of data
# print(ar+10+100*5/10)

[10 20 30 40 60]


1

In [21]:
ar2= np.array([[10.7,200],
               [5,100.4],
               [20.5,500]], dtype =int)

ar.astype(float) # typcasting - change data type of a predefined array
ar2

array([[ 10, 200],
       [  5, 100],
       [ 20, 500]])

In [34]:
ar2[0, 1]   # [row, columns]
ar2[2,0]

ar2[1, :]   #array([  5, 100])
ar2[ [1,2], 1]  #array([100, 500])

ar2[-2: , 0]

ar2[ [1,2], :  ]

array([[  5, 100],
       [ 20, 500]])

In [36]:
ar2[:,0]+10

array([20, 15, 30])

In [39]:
ar2

array([[ 10, 200],
       [  5, 100],
       [ 20, 500]])

In [38]:
ar2.sum()

835

In [41]:
# axis = 0  means reffering to columns
# axis=1 means reffering to rows
ar2.sum(axis=0)

array([ 35, 800])

In [42]:
ar2.sum(axis=1)

array([210, 105, 520])

In [45]:
ar2[1:, :].sum(axis=0)
ar2[1:, :].sum(axis=1)

array([ 25, 600])

In [46]:
ar2

array([[ 10, 200],
       [  5, 100],
       [ 20, 500]])

In [51]:
# where function - 
# np.where(condition ,  o/p when cond is true, o/p when condn false)

np.where(ar2>=100, 'python', ar2)

array([['10', 'python'],
       ['5', 'python'],
       ['20', 'python']], dtype='<U11')

In [71]:
ar4 = np.where((ar2==100)|(ar2==10) , 0, 1)
ar4 =ar4.astype(float)
ar4

array([[0., 1.],
       [1., 0.],
       [1., 1.]])

In [72]:
np.where(ar2>100, True, -1)

array([[-1,  1],
       [-1, -1],
       [-1,  1]])

## SERIES - Multiple rows, two columns (one for index/label)

#### List to SERIES in Pandas

In [78]:
# List to Series
a = np.array([13,14,'15',19.6, 17])

pd.Series(a)
# Series in pandas also gives Index with respect to values/elements in the series

0      13
1      14
2      15
3    19.6
4      17
dtype: object

In [80]:
d = {'a':40,'b':20,'c':30,'d':40}  # dictionaries  -- {key : value}

pd.Series(d)

a    40
b    20
c    30
d    40
dtype: int64

#### CUSTOM INDEX in SERIES

In [82]:
# CUSTOM INDEX in SERIES
# Change by default index to custom index

a = [13,14,'10.00',16, 17.5]
b = ['a','b','c','d', 'e']

s = pd.Series(data = a, index = b)
s2 = s.astype(float)
print(s2)

# Even if one value is string in series, the datatype changes to 'object'
# If integers and float numbers are present in series, datatype is 'float'

a    13.0
b    14.0
c    10.0
d    16.0
e    17.5
dtype: float64


In [21]:
a = np.array([23,33,43,53.5])
a = pd.Series(a)

print(a,type(a))

0    23.0
1    33.0
2    43.0
3    53.5
dtype: float64 <class 'pandas.core.series.Series'>


#### Dictionary to SERIES

In [95]:
d = {'m':10,'n':20,'o':30}

print(d,'\n'*5)  # \n - new line , \t - tab space

pd.Series(data = d) # Dictionary key's convert into Series's labels/indexes

{'m': 10, 'n': 20, 'o': 30} 







m    10
n    20
o    30
dtype: int64

In [5]:
d = { 1 : 10, 'g' : 20, 'd' : 30}

pd.Series(d, dtype = float)

1    10.0
g    20.0
d    30.0
dtype: float64

#### Creating SERIES from SCALER value (single/1 value)

In [20]:
a = pd.Series(6.8 ,index=[100,111,112,113], name = 'Pandas_Series')
a

100    6.8
111    6.8
112    6.8
113    6.8
Name: Pandas Series, dtype: float64

#### Using an Index
The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).

#### Accessing values via Index in SERIES

In [94]:
a = pd.Series([10,100,1000], index=['a','b','c'])
print(a)

print(a['a']) # given actual index name and printing value
print(a[0])  # giving default index will also gove value in series
print(a[0:2])  # slicing the indexes
print(a[['a','c']])  # giving list of indexes to have their respective values

a      10
b     100
c    1000
dtype: int64
a     10
b    100
dtype: int64
a      10
c    1000
dtype: int64


In [30]:
b = pd.Series([100,111,112,113])
c = pd.Series([100,11,12,13])

b = b.astype(float)

print(b%2)

0    0.0
1    1.0
2    0.0
3    1.0
dtype: float64


## DATAFRAME - Multiple rows and columns

#### Creating DataFrame

In [96]:
pd.DataFrame([  [1,2,3], ['50',60,70]  ]) 

0   1   2
0   1   2   3
1  50  60  70

In [111]:
df = pd.DataFrame([  [20,40],  ['abc',60,70]    ]) 
df

# print(df.dtypes) # datatype -- column wise
# print(df.info()) # all the details about the data
# print(df.isna().sum()) # will give total number of NAN values -- column wise

# Nan : Numpy consider NAN to be float, hence is column is float, because in dataframe information is send column-wise

0   1     2
0   20  40   NaN
1  abc  60  70.0

In [120]:
# Dictionary to Dataframe  - equal length for cols

df = pd.DataFrame({'age':['40',20,30,40],
             'salary':[50,60,70.88,80],
             'balance':[90,100,110,120],
              'name':['a','b','c','d']})


df['age']=df['age'].astype(int)
df['ages_2'] = df['age']+10
df['name_age'] = df['age'].astype(str) + df['name']
df

age  salary  balance name  ages_2 name_age
0   40   50.00       90    a      50      40a
1   20   60.00      100    b      30      20b
2   30   70.88      110    c      40      30c
3   40   80.00      120    d      50      40d

In [121]:
np.arange(25) # array of values start from 0 go till 24  - 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [122]:
np.arange(25).size # give count of elements

25

In [128]:
# converting 1D to 2D using reshape function
npdataframe = pd.DataFrame(np.arange(25).reshape(5,5), 
                           columns = ['batch1','batch2','batch3','batch4','batch5'], 
                           index =['a','b','c','d','e']) 

npdataframe


batch1  batch2  batch3  batch4  batch5
a       0       1       2       3       4
b       5       6       7       8       9
c      10      11      12      13      14
d      15      16      17      18      19
e      20      21      22      23      24

In [44]:
# Giving CUSTOM COLUMN NAMES
# Using arange (to also get float values, which is not available in range function) to create a dataframe
df = pd.DataFrame(np.arange(25).reshape(5,5), columns = ['a','b','c','d','e'])
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [45]:
# Creating a dataframe
a = pd.Series( [1,2,3] ) # , index = [1,2,3]
b = pd.Series( np.array([11,12,13]))

# making dataframe
d = pd.DataFrame( {'info 1':a,'info 2':a,'info 3':b} )
d

info 1  info 2  info 3
0       1       1      11
1       2       2      12
2       3       3      13

In [17]:
# Creating a Dataframe
c=pd.Series(         [10,20,30] ,  index = ['python','c++','c#']) # list - index
d=pd.Series(np.array(['1','2','ab']),index = ['python','c++','c#'])  # array - index


e=pd.Series({'python' :100,'c++':200,'java':300})  # dictionary - index
 
f=pd.DataFrame({'A':c,'B':d,'C':e})
f

A    B      C
c#      30.0   ab    NaN
c++     20.0    2  200.0
java     NaN  NaN  300.0
python  10.0    1  100.0

In [44]:
# Creating a Dataframe
pd.DataFrame( {'A':[10,20,30,40],'B':[50,60,70,80],'C':[90,100,110,120]})

A   B    C
0  10  50   90
1  20  60  100
2  30  70  110
3  40  80  120

In [48]:
a = np.arange(10,121,10).reshape(4,-1)

df= pd.DataFrame(a, columns = ['Years Lived','City','Country'])
df

Years Lived  City  Country
0           10    20       30
1           40    50       60
2           70    80       90
3          100   110      120

#### Access Column(s) & Row(s) , Get .head(n) & .tail(n) 

In [59]:
df['Country']
df[['Country', 'City']]

df.Country  # only 1 column can be printed at a time,
# also when col name matched with pre defined function - not to use df.A

0     30
1     60
2     90
3    120
Name: Country, dtype: int32

In [57]:
df.columns # will give the list of column names from a given dataframe

Index(['Years Lived', 'City', 'Country'], dtype='object')

In [55]:
df = df[['Country', 'City', 'Years Lived']]  



student name, studentid, btach id, registration id, phone numer, email address



Country  City  Years Lived
0       30    20           10
1       60    50           40
2       90    80           70
3      120   110          100

#### Get values (.values) , names of columns (.columns), & total number of elements in dataframe (.size)

In [51]:
# Get the data values in form for array
# print('dataframe values:\n',df.values)
# print('specific column values:\n ',df[['A','C']].values)

# # # To see column names of dataframe in form of list
# print('dataframe columns:\n',df.columns)
# print('also dataframe columns\n', df.keys())

# # # Check total number of elements
print('total number, Dimesnion, Shape of DF :',df.size, df.ndim, df.shape)
t = df.shape
print(t[0])

total number, Dimesnion, Shape of DF : 12 2 (4, 3)
4


#### 2D array with decreasing values into DataFrame

In [81]:
# Create dataframe from decreasing values in 2D-array

df2 = pd.DataFrame(np.arange(20,0,-1).reshape(5,-1), 
                   index= ['a','b','c','d','e'], 
                   columns = ['A','B','C','D'])

df2

A   B   C   D
a  20  19  18  17
b  16  15  14  13
c  12  11  10   9
d   8   7   6   5
e   4   3   2   1