# PANDAS

In [2]:
import pandas as pd
import numpy as np   # to make data in form of array

In [ ]:
li = [10, 20, 30, 40, 60]

ar = np.array(li)
print(ar)
ar.ndim # check dimension of data
# print(ar+10+100*5/10)

[10 20 30 40 60]


1

In [ ]:
ar2= np.array([[10.7,200],
               [5,100.4],
               [20.5,500]], dtype =int)

ar.astype(float) # typcasting - change data type of a predefined array
ar2

array([[ 10, 200],
       [  5, 100],
       [ 20, 500]])

In [ ]:
ar2[0, 1]   # [row, columns]
ar2[2,0]

ar2[1, :]   #array([  5, 100])
ar2[ [1,2], 1]  #array([100, 500])

ar2[-2: , 0]

ar2[ [1,2], :  ]

array([[  5, 100],
       [ 20, 500]])

In [ ]:
ar2[:,0]+10

array([20, 15, 30])

In [ ]:
ar2

array([[ 10, 200],
       [  5, 100],
       [ 20, 500]])

In [ ]:
ar2.sum()

835

In [ ]:
# axis = 0  means reffering to columns
# axis=1 means reffering to rows
ar2.sum(axis=0)

array([ 35, 800])

In [ ]:
ar2.sum(axis=1)

array([210, 105, 520])

In [ ]:
ar2[1:, :].sum(axis=0)
ar2[1:, :].sum(axis=1)

array([ 25, 600])

In [ ]:
ar2

array([[ 10, 200],
       [  5, 100],
       [ 20, 500]])

In [ ]:
# where function - 
# np.where(condition ,  o/p when cond is true, o/p when condn false)

np.where(ar2>=100, 'python', ar2)

array([['10', 'python'],
       ['5', 'python'],
       ['20', 'python']], dtype='<U11')

In [ ]:
ar4 = np.where((ar2==100)|(ar2==10) , 0, 1)
ar4 =ar4.astype(float)
ar4

array([[0., 1.],
       [1., 0.],
       [1., 1.]])

In [ ]:
np.where(ar2>100, True, -1)

array([[-1,  1],
       [-1, -1],
       [-1,  1]])

## SERIES - Multiple rows, two columns (one for index/label)

#### List to SERIES in Pandas

In [3]:
# List to Series
a = np.array([13,14,'15',19.6, 17])

pd.Series(a,name='series1')
# Series in pandas also gives Index with respect to values/elements in the series

0      13
1      14
2      15
3    19.6
4      17
Name: series1, dtype: object

In [4]:
d = {'a':40,'b':20,'c':30,'d':40}  # dictionaries  -- {key : value}

d2= pd.Series(d)
print(d2)

a    40
b    20
c    30
d    40
dtype: int64


#### CUSTOM INDEX in SERIES

In [15]:
# CUSTOM INDEX in SERIES
# Change by default index to custom index

a = [13,14,10,'16', 17.9]
b = ['a1','b','c','d', 'e']

s = pd.Series(index=b,data=a)
# s2 = s.astype(int)
print(s)

# Even if one value is string in series, the datatype changes to 'object'
# If integers and float numbers are present in series, datatype is 'float'

a1      13
b       14
c       10
d       16
e     17.9
dtype: object


In [ ]:
a = np.array([23,33,43,53.5])
a = pd.Series(a)

print(a,type(a))

0    23.0
1    33.0
2    43.0
3    53.5
dtype: float64 <class 'pandas.core.series.Series'>


#### Dictionary to SERIES

In [11]:
'hello '*5

[1,2,3]*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [1]:
d = {'m':67,'n':20,'o':30}

print(d,'\n'*5)  # \n - new line , \t - tab space

pd.Series(data = d) # Dictionary key's convert into Series's labels/indexes

{'m': 67, 'n': 20, 'o': 30} 







NameError: name 'pd' is not defined

In [ ]:
d = { 1 : 10, 'g' : 20, 'd' : 30}

pd.Series(d, dtype = float)

1    10.0
g    20.0
d    30.0
dtype: float64

#### Creating SERIES from SCALER value (single/1 value)

In [ ]:
a = pd.Series(6.8 ,index=[100,111,112,113], name = 'Pandas_Series')
a

100    6.8
111    6.8
112    6.8
113    6.8
Name: Pandas Series, dtype: float64

#### Using an Index
The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).

#### Accessing values via Index in SERIES

In [30]:
s1 = pd.Series([10,100,1000], index=['a','a','a'])
print(s1)

# print(s1['a']) # given actual index name and printing value
# print(s1[0])  # giving default index will also gove value in series
print(s1[1:])  # slicing the indexes
# print(s1[['a','c']])  # giving list of indexes to have their respective values

a      10
a     100
a    1000
dtype: int64
a     100
a    1000
dtype: int64


In [41]:
'hello '+'hello '

'hello hello '

In [79]:
a=pd.Series(data=[1,True,'89'])
a2 = pd.Series(data=[1,True,1] , index=[10,20,30])

a2+a
# print(a,'\n',a2)

# pd.Series(['89',True,1])

0     NaN
1     NaN
2     NaN
10    NaN
20    NaN
30    NaN
dtype: object

In [37]:
b = pd.Series([100,111,112,113])
c = pd.Series([100,11,12])

b = b.astype(float)

d=(b+c)//20
print(d)

0    10.0
1     6.0
2     6.0
3     NaN
dtype: float64


## DATAFRAME - Multiple rows and columns

#### Creating DataFrame

In [81]:
pd.DataFrame(np.array([[1,2,3], 
                       ['50',60]]) )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


0
0  [1, 2, 3]
1   [50, 60]

In [92]:
df = pd.DataFrame([[20,40],  ['abc',60,70]]) 
df

# print(df.dtypes) # datatype -- column wise
# print(df.info()) # all the details about the data
# print(df.isna().sum()) # will give total number of NAN values -- column wise

# Nan : Numpy consider NAN to be float, hence is column is float, because in dataframe information is send column-wise

0   1     2
0   20  40   NaN
1  abc  60  70.0

In [173]:
pd.DataFrame(data=np.array([i for i in range(81,86)])).dtypes



0    int64
dtype: object

In [114]:
df2=pd.DataFrame(data=np.array([i for i in range(81,86)])).T
df2.columns=['c1','c2','c3','c4','c5']
df2

c1  c2  c3  c4  c5
0  81  82  83  84  85

In [121]:
df3=pd.DataFrame([[20,40],
                  [12,'Siri',True,56],
                  ['snape',112,False]])
df3.dtypes  # None --> object, NaN ---> Float

0     object
1     object
2     object
3    float64
dtype: object

In [97]:
df1=pd.DataFrame(data = np.array([i for i in range(81,86)]),index = [i for i in range(10,15)], columns= ['values'])
print(df1)


    values
10      81
11      82
12      83
13      84
14      85


In [126]:
# Dictionary to Dataframe  - equal length for cols

df = pd.DataFrame({'age':['40',20,30,40],
             'salary':[50,60,70.88,80],
             'balance':[90,100,110,120],
              'name':['a','b','c','d']})
df['age']=df['age'].astype(int)
df['ages_2'] = df['age']+10
df['name_age'] = df['age'].astype(str) + df['name']
print(df.dtypes)
df

age           int64
salary      float64
balance       int64
name         object
ages_2        int64
name_age     object
dtype: object


age  salary  balance name  ages_2 name_age
0   40   50.00       90    a      50      40a
1   20   60.00      100    b      30      20b
2   30   70.88      110    c      40      30c
3   40   80.00      120    d      50      40d

In [ ]:
np.arange(25) # array of values start from 0 go till 24  - 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(25).size # give count of elements

25

In [ ]:
# converting 1D to 2D using reshape function
npdataframe = pd.DataFrame(np.arange(25).reshape(5,5), 
                           columns = ['batch1','batch2','batch3','batch4','batch5'], 
                           index =['a','b','c','d','e']) 

npdataframe


batch1  batch2  batch3  batch4  batch5
a       0       1       2       3       4
b       5       6       7       8       9
c      10      11      12      13      14
d      15      16      17      18      19
e      20      21      22      23      24

In [ ]:
# Giving CUSTOM COLUMN NAMES
# Using arange (to also get float values, which is not available in range function) to create a dataframe
df = pd.DataFrame(np.arange(25).reshape(5,5), columns = ['a','b','c','d','e'])
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [128]:
# Creating a dataframe
a = pd.Series( [1,2,3] ) 
b = pd.Series( np.array([11,12,13]))

# making dataframe
d = pd.DataFrame( {'info 1':a+100,
                   'info 2':b+100,
                   'info 3':b} )
d

info 1  info 2  info 3
0     101     111      11
1     102     112      12
2     103     113      13

In [ ]:
# Creating a Dataframe
c=pd.Series(         [10,20,30] ,  index = ['python','c++','c#']) # list - index
d=pd.Series(np.array(['1','2','ab']),index = ['python','c++','c#'])  # array - index


e=pd.Series({'python' :100,'c++':200,'java':300})  # dictionary - index
 
f=pd.DataFrame({'A':c,'B':d,'C':e})
f

A    B      C
c#      30.0   ab    NaN
c++     20.0    2  200.0
java     NaN  NaN  300.0
python  10.0    1  100.0

In [ ]:
# Creating a Dataframe
pd.DataFrame( {'A':[10,20,30,40],'B':[50,60,70,80],'C':[90,100,110,120]})

A   B    C
0  10  50   90
1  20  60  100
2  30  70  110
3  40  80  120

In [129]:
a = np.arange(10,121,10).reshape(4,-1)

df= pd.DataFrame(a, columns = ['Years Lived','City','Country'])
df

Years Lived  City  Country
0           10    20       30
1           40    50       60
2           70    80       90
3          100   110      120

#### Access Column(s) & Row(s) , Get .head(n) & .tail(n) 

In [132]:
df['country_age']= df['Country']/df['Years Lived']
df

Years Lived  City  Country  country_age
0           10    20       30     3.000000
1           40    50       60     1.500000
2           70    80       90     1.285714
3          100   110      120     1.200000

In [135]:
df['Country']
df[['country_age','Country', 'City']]

df.Country  # only 1 column can be printed at a time,
# also when col name matched with pre defined function - not to use df.A

country_age  Country  City
0     3.000000       30    20
1     1.500000       60    50
2     1.285714       90    80
3     1.200000      120   110

In [ ]:
df.columns # will give the list of column names from a given dataframe

Index(['Years Lived', 'City', 'Country'], dtype='object')

In [146]:
df = df[['Country', 'City', 'Years Lived']]  
df.values

df['Country'] = df.Country.values

df

Country  City  Years Lived
0       30    20           10
1       60    50           40
2       90    80           70
3      120   110          100

#### Get values (.values) , names of columns (.columns), & total number of elements in dataframe (.size)

In [ ]:
# Get the data values in form for array
print('dataframe values:\n',df.values)
print('specific column values:\n ',df['Country'].values)

# # # To see column names of dataframe in form of list
print('dataframe columns:\n',df.columns)
print('also dataframe columns\n', df.keys())

# # # Check total number of elements
print('total number, Dimesnion, Shape of DF :',df.size, df.ndim, df.shape)
t = df.shape
print(t[0])

total number, Dimesnion, Shape of DF : 12 2 (4, 3)
4


#### 2D array with decreasing values into DataFrame

In [155]:
np.arange(20,0,-1).size

20

In [157]:
np.arange(20,0,-1).reshape(5,-1)#(row, col)

array([[20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [ ]:
# Create dataframe from decreasing values in 2D-array

df2 = pd.DataFrame(np.arange(20,0,-1).reshape(5,-1), 
                   index= ['a','b','c','d','e'], 
                   columns = ['A','B','C','D'])

df2

A   B   C   D
a  20  19  18  17
b  16  15  14  13
c  12  11  10   9
d   8   7   6   5
e   4   3   2   1